/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity */
        get: operations["activity_api_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Directory */
        get: operations["directory_api_users_directory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch */
        patch: operations["patch_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/users/{user_id}/reset-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Link */
        post: operations["reset_link_api_users__user_id__reset_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_invitations_get"];
        put?: never;
        /** Create */
        post: operations["create_api_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke */
        delete: operations["revoke_api_invitations__invitation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accept-invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_api_auth_accept_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vocab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_vocab_get"];
        put?: never;
        /** Create */
        post: operations["create_api_vocab_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vocab/{term_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch */
        patch: operations["patch_api_vocab__term_id__patch"];
        trace?: never;
    };
    "/api/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_items_get"];
        put?: never;
        /** Create */
        post: operations["create_api_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One */
        get: operations["get_one_api_items__item_id__get"];
        put?: never;
        post?: never;
        /** Soft Delete */
        delete: operations["soft_delete_api_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Patch */
        patch: operations["patch_api_items__item_id__patch"];
        trace?: never;
    };
    "/api/items/{item_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore */
        post: operations["restore_api_items__item_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_items__item_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_items__item_id__updates_get"];
        put?: never;
        /** Create */
        post: operations["create_api_items__item_id__updates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{item_id}/updates/{update_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove */
        delete: operations["remove_api_items__item_id__updates__update_id__delete"];
        options?: never;
        head?: never;
        /** Patch */
        patch: operations["patch_api_items__item_id__updates__update_id__patch"];
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/excel/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview */
        post: operations["preview_api_import_excel_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/excel/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit */
        post: operations["commit_api_import_excel_commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Excel
         * @description Binary download; this is the one endpoint that does not use the JSON envelope.
         */
        get: operations["export_excel_api_export_excel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInviteRequest */
        AcceptInviteRequest: {
            /** Token */
            token: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** AuditEventOut */
        AuditEventOut: {
            /** Id */
            id: number;
            /** Program Id */
            program_id: number | null;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id: number;
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: number;
            /** Actor Name */
            actor_name: string;
            /** Actor Org */
            actor_org: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Changes */
            changes: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string;
        };
        /** Body_commit_api_import_excel_commit_post */
        Body_commit_api_import_excel_commit_post: {
            /** File */
            file: string;
            /**
             * Overrides
             * @default {}
             */
            overrides: string;
        };
        /** Body_preview_api_import_excel_preview_post */
        Body_preview_api_import_excel_preview_post: {
            /** File */
            file: string;
            /**
             * Overrides
             * @default {}
             */
            overrides: string;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Open Total */
            open_total: number;
            /** Open By Status */
            open_by_status: {
                [key: string]: number;
            };
            /** Open P1 */
            open_p1: number;
            /** Overdue Count */
            overdue_count: number;
            /** Due Soon Count */
            due_soon_count: number;
            /** Stale Count */
            stale_count: number;
            needs_attention: components["schemas"]["NeedsAttention"];
            /** By Group */
            by_group: {
                [key: string]: number;
            };
            /** By Owner Org */
            by_owner_org: {
                [key: string]: number;
            };
            /** Recent Activity */
            recent_activity: components["schemas"]["AuditEventOut"][];
        };
        /** Envelope[DashboardSummary] */
        Envelope_DashboardSummary_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["DashboardSummary"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[HealthOut] */
        Envelope_HealthOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["HealthOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[ImportCommitOut] */
        Envelope_ImportCommitOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["ImportCommitOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[ImportPreviewOut] */
        Envelope_ImportPreviewOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["ImportPreviewOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[InvitationCreatedOut] */
        Envelope_InvitationCreatedOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["InvitationCreatedOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[InvitationOut] */
        Envelope_InvitationOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["InvitationOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[ItemOut] */
        Envelope_ItemOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["ItemOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[NoneType] */
        Envelope_NoneType_: {
            /** Success */
            success: boolean;
            /** Data */
            data?: null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[ResetLinkOut] */
        Envelope_ResetLinkOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["ResetLinkOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[UpdateOut] */
        Envelope_UpdateOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["UpdateOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[UserOut] */
        Envelope_UserOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["UserOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[VocabTermOut] */
        Envelope_VocabTermOut_: {
            /** Success */
            success: boolean;
            data?: components["schemas"]["VocabTermOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[list[AuditEventOut]] */
        Envelope_list_AuditEventOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["AuditEventOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[list[InvitationOut]] */
        Envelope_list_InvitationOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["InvitationOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[list[ItemOut]] */
        Envelope_list_ItemOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["ItemOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[list[UpdateOut]] */
        Envelope_list_UpdateOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["UpdateOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[list[UserBrief]] */
        Envelope_list_UserBrief__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["UserBrief"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[list[UserOut]] */
        Envelope_list_UserOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["UserOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** Envelope[list[VocabTermOut]] */
        Envelope_list_VocabTermOut__: {
            /** Success */
            success: boolean;
            /** Data */
            data?: components["schemas"]["VocabTermOut"][] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            meta?: components["schemas"]["Meta"] | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Fields */
            fields?: {
                [key: string]: string;
            } | null;
            /** Request Id */
            request_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Database */
            database: string;
        };
        /** ImportCommitOut */
        ImportCommitOut: {
            /** Items Created */
            items_created: number;
            /** Updates Created */
            updates_created: number;
            /** Audit Event Id */
            audit_event_id: number;
        };
        /** ImportPreviewOut */
        ImportPreviewOut: {
            /** File Name */
            file_name: string;
            /** Total Rows */
            total_rows: number;
            /** Actions */
            actions: number;
            /** Notes */
            notes: number;
            /** Updates */
            updates: number;
            /** Unmapped */
            unmapped: {
                [key: string]: string[];
            };
            /** Errors */
            errors: string[];
            /** Warnings */
            warnings: components["schemas"]["ImportWarningOut"][];
            /** Committable */
            committable: boolean;
            /** Rows */
            rows: components["schemas"]["PreviewRowOut"][];
        };
        /** ImportWarningOut */
        ImportWarningOut: {
            /** Excel Row */
            excel_row: number;
            /** Entry No */
            entry_no: number | null;
            /** Message */
            message: string;
        };
        /** InvitationCreate */
        InvitationCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Org
             * @enum {string}
             */
            org: "gensci" | "yarrow";
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "member";
        };
        /** InvitationCreatedOut */
        InvitationCreatedOut: {
            invitation: components["schemas"]["InvitationOut"];
            /** Url */
            url: string;
        };
        /** InvitationOut */
        InvitationOut: {
            /** Id */
            id: number;
            /** Purpose */
            purpose: string;
            /** Email */
            email: string;
            /** Org */
            org: string | null;
            /** Role */
            role: string | null;
            /** User Id */
            user_id: number | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Accepted At */
            accepted_at: string | null;
            /** Created By */
            created_by: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ItemBrief */
        ItemBrief: {
            /** Id */
            id: number;
            /** Entry No */
            entry_no: number;
            /** Title */
            title: string;
            /** Status */
            status: string | null;
            /** Priority */
            priority: string | null;
            /** Owner Org */
            owner_org: string;
            /** Due On */
            due_on: string | null;
            /** Last Update On */
            last_update_on: string | null;
        };
        /** ItemCreate */
        ItemCreate: {
            /**
             * Kind
             * @default action
             * @enum {string}
             */
            kind: "action" | "note";
            /** Title */
            title: string;
            /**
             * Details
             * @default
             */
            details: string;
            /** Group */
            group: string;
            /** Category */
            category?: string | null;
            /**
             * Owner Org
             * @enum {string}
             */
            owner_org: "gensci" | "yarrow" | "joint";
            /** Assignee Id */
            assignee_id?: number | null;
            /** Status */
            status?: ("open" | "in_progress" | "blocked" | "on_hold" | "completed" | "cancelled") | null;
            /** Priority */
            priority?: ("p1" | "p2" | "p3") | null;
            /** Raised On */
            raised_on?: string | null;
            /** Source */
            source?: string | null;
            /** Due On */
            due_on?: string | null;
            /**
             * Notes Risks
             * @default
             */
            notes_risks: string;
            /**
             * File Path
             * @default
             */
            file_path: string;
        };
        /** ItemOut */
        ItemOut: {
            /** Id */
            id: number;
            /** Program Id */
            program_id: number;
            /** Entry No */
            entry_no: number;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Details */
            details: string;
            /** Group */
            group: string;
            /** Category */
            category: string | null;
            /** Owner Org */
            owner_org: string;
            /** Assignee Id */
            assignee_id: number | null;
            /** Status */
            status: string | null;
            /** Priority */
            priority: string | null;
            /**
             * Raised On
             * Format: date
             */
            raised_on: string;
            /** Source */
            source: string | null;
            /** Due On */
            due_on: string | null;
            /** Completed On */
            completed_on: string | null;
            /** Notes Risks */
            notes_risks: string;
            /** File Path */
            file_path: string;
            /** Created By */
            created_by: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated By */
            updated_by: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Last Update On */
            last_update_on?: string | null;
        };
        /** ItemPatch */
        ItemPatch: {
            /** Kind */
            kind?: ("action" | "note") | null;
            /** Title */
            title?: string | null;
            /** Details */
            details?: string | null;
            /** Group */
            group?: string | null;
            /** Category */
            category?: string | null;
            /** Owner Org */
            owner_org?: ("gensci" | "yarrow" | "joint") | null;
            /** Assignee Id */
            assignee_id?: number | null;
            /** Status */
            status?: ("open" | "in_progress" | "blocked" | "on_hold" | "completed" | "cancelled") | null;
            /** Priority */
            priority?: ("p1" | "p2" | "p3") | null;
            /** Raised On */
            raised_on?: string | null;
            /** Source */
            source?: string | null;
            /** Due On */
            due_on?: string | null;
            /** Notes Risks */
            notes_risks?: string | null;
            /** File Path */
            file_path?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Meta */
        Meta: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Limit */
            limit: number;
        };
        /** NeedsAttention */
        NeedsAttention: {
            /** Overdue */
            overdue: components["schemas"]["ItemBrief"][];
            /** Due Soon */
            due_soon: components["schemas"]["ItemBrief"][];
            /** Stale */
            stale: components["schemas"]["ItemBrief"][];
        };
        /** PreviewRowOut */
        PreviewRowOut: {
            /** Excel Row */
            excel_row: number;
            /** Entry No */
            entry_no: number | null;
            /** Kind */
            kind: string;
            /** Title */
            title: string;
            /** Group */
            group: string | null;
            /** Category */
            category: string | null;
            /** Owner Org */
            owner_org: string | null;
            /** Status */
            status: string | null;
            /** Priority */
            priority: string | null;
            /**
             * Raised On
             * Format: date
             */
            raised_on: string;
            /** Due On */
            due_on: string | null;
            /** Updates */
            updates: number;
            /** Warnings */
            warnings: string[];
        };
        /** ResetLinkOut */
        ResetLinkOut: {
            /** Url */
            url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** UpdateCreate */
        UpdateCreate: {
            /** Body */
            body: string;
            /** Occurred On */
            occurred_on?: string | null;
        };
        /** UpdateOut */
        UpdateOut: {
            /** Id */
            id: number;
            /** Item Id */
            item_id: number;
            /** Author Id */
            author_id: number;
            /** Author Name */
            author_name: string;
            /** Author Org */
            author_org: string;
            /** Body */
            body: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Edited At */
            edited_at: string | null;
        };
        /** UpdatePatch */
        UpdatePatch: {
            /** Body */
            body?: string | null;
            /** Occurred On */
            occurred_on?: string | null;
        };
        /** UserBrief */
        UserBrief: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Org */
            org: string;
            /** Is Active */
            is_active: boolean;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Org */
            org: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Last Login At */
            last_login_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** UserPatch */
        UserPatch: {
            /** Name */
            name?: string | null;
            /** Org */
            org?: ("gensci" | "yarrow") | null;
            /** Role */
            role?: ("admin" | "member") | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VocabTermCreate */
        VocabTermCreate: {
            /**
             * Field
             * @enum {string}
             */
            field: "group" | "category";
            /** Value */
            value: string;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
        };
        /** VocabTermOut */
        VocabTermOut: {
            /** Id */
            id: number;
            /** Program Id */
            program_id: number;
            /** Field */
            field: string;
            /** Value */
            value: string;
            /** Sort Order */
            sort_order: number;
            /** Is Active */
            is_active: boolean;
        };
        /** VocabTermPatch */
        VocabTermPatch: {
            /** Value */
            value?: string | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HealthOut_"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UserOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_NoneType_"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UserOut_"];
                };
            };
        };
    };
    activity_api_activity_get: {
        parameters: {
            query?: {
                org?: ("gensci" | "yarrow") | null;
                actor_id?: number | null;
                entity_type?: ("item" | "user" | "invitation" | "vocab_term" | "import") | null;
                since?: string | null;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_AuditEventOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_UserOut__"];
                };
            };
        };
    };
    directory_api_users_directory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_UserBrief__"];
                };
            };
        };
    };
    patch_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UserOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_link_api_users__user_id__reset_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ResetLinkOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_invitations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_InvitationOut__"];
                };
            };
        };
    };
    create_api_invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_InvitationCreatedOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_invitations__invitation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_InvitationOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_api_auth_accept_invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UserOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_vocab_get: {
        parameters: {
            query?: {
                field?: ("group" | "category") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_VocabTermOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_vocab_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabTermCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_VocabTermOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_api_vocab__term_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VocabTermPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_VocabTermOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_items_get: {
        parameters: {
            query?: {
                sort?: string;
                direction?: "asc" | "desc";
                page?: number;
                limit?: number;
                status?: ("open" | "in_progress" | "blocked" | "on_hold" | "completed" | "cancelled")[] | null;
                priority?: ("p1" | "p2" | "p3")[] | null;
                group?: string[] | null;
                category?: string[] | null;
                owner_org?: ("gensci" | "yarrow" | "joint")[] | null;
                kind?: ("action" | "note") | null;
                assignee_id?: number | null;
                due_before?: string | null;
                due_after?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_ItemOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ItemOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_one_api_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ItemOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soft_delete_api_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ItemOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_api_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ItemOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_api_items__item_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ItemOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_items__item_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_AuditEventOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_api_items__item_id__updates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_UpdateOut__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_items__item_id__updates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UpdateOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_items__item_id__updates__update_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
                update_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_NoneType_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_api_items__item_id__updates__update_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
                update_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UpdateOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DashboardSummary_"];
                };
            };
        };
    };
    preview_api_import_excel_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_api_import_excel_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ImportPreviewOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_api_import_excel_commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_commit_api_import_excel_commit_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ImportCommitOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_excel_api_export_excel_get: {
        parameters: {
            query?: {
                status?: ("open" | "in_progress" | "blocked" | "on_hold" | "completed" | "cancelled")[] | null;
                priority?: ("p1" | "p2" | "p3")[] | null;
                group?: string[] | null;
                category?: string[] | null;
                owner_org?: ("gensci" | "yarrow" | "joint")[] | null;
                kind?: ("action" | "note") | null;
                assignee_id?: number | null;
                due_before?: string | null;
                due_after?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
