"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-06 11:53:06.317143

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('org', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("org IN ('gensci', 'yarrow')", name=op.f('ck_app_user_org_in')),
    sa.CheckConstraint("role IN ('admin', 'member')", name=op.f('ck_app_user_role_in')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_user_email'), ['email'], unique=True)

    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program')),
    sa.UniqueConstraint('code', name=op.f('uq_program_code'))
    )
    op.create_table('action_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('entry_no', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('owner_org', sa.String(length=16), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.String(length=4), nullable=True),
    sa.Column('raised_on', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('notes_risks', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(kind = 'note' AND status IS NULL) OR (kind = 'action' AND status IS NOT NULL)", name=op.f('ck_action_item_status_matches_kind')),
    sa.CheckConstraint("kind IN ('action', 'note')", name=op.f('ck_action_item_kind_in')),
    sa.CheckConstraint("owner_org IN ('gensci', 'yarrow', 'joint')", name=op.f('ck_action_item_owner_org_in')),
    sa.CheckConstraint("priority IS NULL OR priority IN ('p1', 'p2', 'p3')", name=op.f('ck_action_item_priority_in')),
    sa.CheckConstraint("status IS NULL OR status IN ('open', 'in_progress', 'blocked', 'on_hold', 'completed', 'cancelled')", name=op.f('ck_action_item_status_in')),
    sa.ForeignKeyConstraint(['assignee_id'], ['app_user.id'], name=op.f('fk_action_item_assignee_id_app_user')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_action_item_created_by_app_user')),
    sa.ForeignKeyConstraint(['deleted_by'], ['app_user.id'], name=op.f('fk_action_item_deleted_by_app_user')),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('fk_action_item_program_id_program')),
    sa.ForeignKeyConstraint(['updated_by'], ['app_user.id'], name=op.f('fk_action_item_updated_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_item')),
    sa.UniqueConstraint('program_id', 'entry_no', name=op.f('uq_action_item_program_id_entry_no'))
    )
    with op.batch_alter_table('action_item', schema=None) as batch_op:
        batch_op.create_index('ix_action_item_program_due', ['program_id', 'due_on'], unique=False)
        batch_op.create_index('ix_action_item_program_status', ['program_id', 'status'], unique=False)

    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.CheckConstraint("action IN ('created', 'updated', 'deleted', 'restored', 'status_changed', 'update_posted', 'update_edited', 'update_deleted', 'role_changed', 'deactivated', 'reactivated', 'invited', 'revoked', 'reset_link_issued', 'imported')", name=op.f('ck_audit_event_action_in')),
    sa.CheckConstraint("entity_type IN ('item', 'user', 'invitation', 'vocab_term', 'import')", name=op.f('ck_audit_event_entity_type_in')),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_audit_event_actor_id_app_user')),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('fk_audit_event_program_id_program')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index('ix_audit_event_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('org', sa.String(length=16), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("org IS NULL OR org IN ('gensci', 'yarrow')", name=op.f('ck_invitation_org_in')),
    sa.CheckConstraint("purpose IN ('invite', 'reset')", name=op.f('ck_invitation_purpose_in')),
    sa.CheckConstraint("role IS NULL OR role IN ('admin', 'member')", name=op.f('ck_invitation_role_in')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_invitation_created_by_app_user')),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_invitation_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitation_token_hash'))
    )
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitation_email'), ['email'], unique=False)

    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_user_session_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_session')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_session_token_hash'))
    )
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_session_user_id'), ['user_id'], unique=False)

    op.create_table('vocab_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("field IN ('group', 'category')", name=op.f('ck_vocab_term_field_in')),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('fk_vocab_term_program_id_program')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocab_term')),
    sa.UniqueConstraint('program_id', 'field', 'value', name=op.f('uq_vocab_term_program_id_field_value'))
    )
    op.create_table('item_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['app_user.id'], name=op.f('fk_item_update_author_id_app_user')),
    sa.ForeignKeyConstraint(['item_id'], ['action_item.id'], name=op.f('fk_item_update_item_id_action_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_update'))
    )
    with op.batch_alter_table('item_update', schema=None) as batch_op:
        batch_op.create_index('ix_item_update_item_occurred', ['item_id', 'occurred_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_update', schema=None) as batch_op:
        batch_op.drop_index('ix_item_update_item_occurred')

    op.drop_table('item_update')
    op.drop_table('vocab_term')
    with op.batch_alter_table('user_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_session_user_id'))

    op.drop_table('user_session')
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitation_email'))

    op.drop_table('invitation')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_occurred_at'))
        batch_op.drop_index('ix_audit_event_entity')

    op.drop_table('audit_event')
    with op.batch_alter_table('action_item', schema=None) as batch_op:
        batch_op.drop_index('ix_action_item_program_status')
        batch_op.drop_index('ix_action_item_program_due')

    op.drop_table('action_item')
    op.drop_table('program')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_user_email'))

    op.drop_table('app_user')
    # ### end Alembic commands ###
